// 11-vite-mf/11c-container/src/components/header/Header.tsx
import React from 'react'
import {Link} from "react-router-dom";

type HeaderProps = {
    isLogin: boolean,
    onLoginButtonClick: () => void;
}

const Header: React.FC<HeaderProps> = (props) => {
    const { onLoginButtonClick } = props;

    const handleClick = () => {
        onLoginButtonClick()
    }

    return (
        <nav className="navbar navbar-light bg-light">
            <Link to="/" className="btn btn-link">Webpack Module Federation</Link>
            <form className="form-inline">
                <button className="btn btn-outline-success" type="button" onClick={handleClick}>{ !props.isLogin ? 'Login' : 'Logout'}</button>
            </form>
        </nav>
    )
}

export default Header

// 10-module-federation/10B-dashboard/src/components/header/Header.vue
<script setup>
import RefreshIcon from "../icons/svg/RefreshIcon.vue";
import FilterIcon from "../icons/svg/FilterIcon.vue";
const emit = defineEmits(['filter-click', 'refresh-click'])
</script>

<template>
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand mx-1" href="#">Dashboard</a>
  <form class="form-inline">
    <button class="btn btn-sm btn-outline-success mx-1" type="button" @click="emit('refresh-click')">
      <RefreshIcon :size="12" /> Refresh
    </button>
    <button class="btn btn-sm btn-outline-success mx-1" type="button" @click="emit('filter-click')">
      <FilterIcon :size="12" /> Filter
    </button>
  </form>
</nav>
</template>
